apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse-week12-lab
  name: ctse-week12-lab
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse-week12-lab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse-week12-lab
    spec:
      containers:
      - image: it19513188/week-12-lab:{{tag}}
        imagePullPolicy: Always
        name: week-12-lab
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}