apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-week12-lab
  name: ctse-week12-lab
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ctse-week12-lab
status:
  loadBalancer: {}